name: Auto build image
on:
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Auto build image
    if: ${{ github.event.comment.body == '/make build v1.20.14 ADM64' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

      - name: Auto build image
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          run: |
            wget https://dl.k8s.io/v1.20.14/kubernetes-server-linux-amd64.tar.gz
            tar -xvf kubernetes-server-linux-amd64.tar.gz
            rm -rf kubernetes-server-linux-amd64.tar.gz
            cd kubernetes/server/bin
            cat << EOF >>Kubefile
            FROM scratch
            COPY kubectl ./bin
            COPY kubeadm ./bin
            COPY kubelet ./bin
            EOF
            sealer build -f Kubefile -m lite -f kubernetes:v1.20.14 .