name: Sample workflow using golang-security-action

on: [push, pull_request]

jobs:
  golang-security-action:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout Source
#        uses: actions/checkout@v2
#      - name: Run Gosec Security Scanner
#        uses: securego/gosec@master
      - uses: actions/checkout@v2
      - uses: ynniss/golang-security-action@master
        with:
          CODE_PATH: "./..."